id: IC4C02C25
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T11:48:06+00:00'
last_modified: '2022-06-08T12:01:00.168452+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21623
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་ལེའུ་བཞིའི་ཊཱི་ཀ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    507E:
      image_group_id: I4218
      title: ''
      total_pages: 810
      order: 1
      base_file: 507E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
