id: P009577
initial_creation_type: ocr
source_metadata:
  id: bdr:W21623
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་ལེའུ་བཞིའི་ཊཱི་ཀ
  author: ''
  volumes:
    84ade6c1cbfb44a3bec532b0394b3e66:
      image_group_id: I4218
      title: ''
      volume_number: 1
      total_pages: 810
      base_file: v001.txt
